version: "3"

services:
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    environment: 
      - PHP_OPCACHE_REVALIDATE_FREQUENCY=0
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    volumes:
      - ./application:/var/www/html
    user: "1000"
    networks:
      - appnet

  server:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./application:/var/www/html
    ports:
      - 80:80
    networks:
      - appnet

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - appnet

  cache:
    image: redis:alpine
    volumes:
      - cachedata:/data
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
  dbdata:
    driver: "local"
  cachedata:
    driver: "local"